"""
Django settings for my_web_project project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from dotenv import load_dotenv
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l6mbzxl6)$7p#^)i18^3*bu*ix6_kuoj6ule_acanu9&b%el#y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# 加載 .env 文件
# load_dotenv()

# email設定
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'                                       # 郵件伺服器
EMAIL_PORT = 587
EMAIL_USE_TLS = True                                                # TLS 加密
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER                                # 默認發送者信箱

# PayPal 設定
PAYPAL_RECEIVER_EMAIL = 'sb-pqhj535147418@business.example.com'     # PayPal帳號的信箱
PAYPAL_TEST = True                                                  # 是否為沙盒環境

# 路徑設定，這是 django-filer 處理文件儲存的位置
DEFAULT_FILE_STORAGE = 'filer.storage.FilerStorage'

# 設定媒體檔案儲存的路徑
MEDIA_URL = '/media/'                                               # 網站上存取媒體檔案的 URL 路徑
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')                        # 實際儲存圖片的根目錄

# 處理縮圖
THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'easy_thumbnails.processors.scale_and_crop',
    'easy_thumbnails.processors.filters',
)

FILER_STORAGES = {
    'public': {
        'main': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
            'OPTIONS': {
                'location': os.path.join(BASE_DIR, 'media/filer'),          # 儲存路徑
                'base_url': '/media/filer/', 
            },
            'UPLOAD_TO': 'filer.utils.generate_filename.randomized',        # 使用隨機命名
            'UPLOAD_TO_PREFIX': 'filer_public',                             # 儲存目錄前綴
        },
        'thumbnails': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
            'OPTIONS': {
                'location': os.path.join(BASE_DIR, 'media/filer_thumbnails'),
                'base_url': '/media/filer_thumbnails/',
            },
        },
    },
    'private': {
        'main': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
            'OPTIONS': {
                'location': os.path.join(BASE_DIR, 'smedia/filer_private'),
                'base_url': '/smedia/filer_private/',
            },
            'UPLOAD_TO': 'filer.utils.generate_filename.randomized',
            'UPLOAD_TO_PREFIX': 'filer_private', 
        },
        'thumbnails': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
            'OPTIONS': {
                'location': os.path.join(BASE_DIR, 'smedia/filer_thumbnails_private'),
                'base_url': '/smedia/filer_thumbnails_private/',
            },
        },
    },
}



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'firstapp',
    'shop',
    'panda_app',
    'captcha',
    'registration',
    'filer',                            # django-filer
    'easy_thumbnails',
    'paypal.standard.ipn',              # django-paypal
]

CART_SESSION_ID = 'cart'

# 註冊後帳號有效天數
ACCOUNT_ACTIVATION_DAYS = 7

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

LOGIN_REDIRECT_URL = 'shop:product'         # 注意使用 app_name:url_name 的格式
LOGIN_URL = 'shop:login'                    # 未登入時重定向到登入頁

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'my_web_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # 預設會搜索根目錄下的 templates 資料夾
            os.path.join(BASE_DIR, 'templates'),                # 根目錄下的 templates 資料夾
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.category_list',
            ],
        },
    },
]

SESSION_EXPIRE_AT_BOWSER_CLOSE = True

WSGI_APPLICATION = 'my_web_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'my_web',
        'USER': 'postgres',
        'PASSWORD': '1234',
        'HOST' : 'localhost',
        'PORT' : '5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'zh-Hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'shop/static'),              # 將 shop/static 資料夾加入靜態檔案目錄
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
